### ISSUE TITLE
Missing morepath-cookiecutter

### ISSUE THREAD

**Issue by henri-hulski** [taschini/morepath-umbrella#1]

**Comment by taschini** [comment]
This umbrella project groups together libraries, extensions and demo apps, all things that can be easily tested together.  The Morepath Cookiecutter (like the [benchmark](https://github.com/faassen/welcome-bench)) is none of these things (it's a recipe to be used by a developer support tool) and its structure does not really fit in here.

It is tested, however, in a different project, [morepath-cookiecutter-tester](/taschini/morepath-cookiecutter-tester), which is also not part of this umbrella project for exactly the same reason.

**Comment by henri-hulski** [comment]
Understand.
