### ISSUE TITLE
test_flake8_setup failed with flake8 3.0

### ISSUE THREAD

**Issue by henri-hulski** [taschini/morepath-umbrella#2]
When installing the umbrella as described in the docs I get flake8 version 3.0.3.
With this version test_flake8_setup failes with the error message:

```
    def test_flake8_setup(subproject):
>       from flake8.main import check_file
E       ImportError: cannot import name check_file
```

The reason is, that flak8 3 doesn't support flake8.main.check_file anymore.
A fix would be to change the dependency in requirements.txt to

```
# Umbrella dependencies
flake8 < 3.0
```

**Comment by taschini** [comment]
Thanks, fixed that in [39462cad0d35ce9a7588dc76919a69b9ee0fd50e](https://github.com/taschini/morepath-umbrella/commit/39462cad0d35ce9a7588dc76919a69b9ee0fd50e).
